# --- main ---
ANIMO_MINIMO = 40
PUBLICO_ACCION = 40
PUBLICO_HIT = 30
PUBLICO_FIN_ARTISTA = 50

# --- dcconcierto ---

PUBLICO_INICIAL = 100
PUBLICO_EXITO = 50
PROBABILIDAD_EVENTO = 0.3
ARTISTAS_ESCOGIDOS = 3
AFINIDAD_LLUVIA = 20
PUBLICO_TERREMOTO = 30
AFINIDAD_OLA_CALOR = 10
PUBLICO_OLA_CALOR = 10

# --- artista ---
AFINIDAD_MIN = 0
AFINIDAD_MAX = 100
AFINIDAD_HIT = 30
AFINIDAD_INICIAL = 0
AFINIDAD_PUBLICO_POP = 60
AFINIDAD_STAFF_POP = 40
AFINIDAD_PUBLICO_ROCK = 20
AFINIDAD_STAFF_ROCK = 80
AFINIDAD_PUBLICO_TRAP_CHILENO = 30
AFINIDAD_STAFF_TRAP_CHILENO  = 70
AFINIDAD_PUBLICO_REG = 50
AFINIDAD_STAFF_REG = 50
AFINIDAD_ACCION_POP = 30
AFINIDAD_ACCION_ROCK = 50
AFINIDAD_ACCION_TRAP_CHILENO  = 40
AFINIDAD_ACCION_REG = 20
